package main

import (
	"testing"
	"time"
)

func TestAssessmentRanksWeakAccountSystems(t *testing.T){snap:=AccountSnapshot{Source:"test",World:6,CapturedAt:time.Now(),Systems:map[string]SystemState{"alchemy":{Progress:.20,Ready:true},"stamps":{Progress:.80,Ready:true},"sailing":{Progress:.60,Ready:true},"talents":{Progress:.95,Ready:true}},Characters:[]CharacterSnapshot{{Name:"Mage",Class:"Bubo",Level:500,Active:true}}};a:=buildAssessment(GameState{Running:true,Foreground:true},snap);if len(a.Top)==0{t.Fatal("expected recommendations")};if a.Top[0].System!="alchemy"{t.Fatalf("expected alchemy first, got %s",a.Top[0].System)};if a.Top[0].Character!="Mage"{t.Fatalf("expected Bubo assignment, got %s",a.Top[0].Character)}}

func TestAssessmentRequiresCalibrationForAutomation(t *testing.T){snap:=AccountSnapshot{Source:"test",World:6,CapturedAt:time.Now(),Systems:map[string]SystemState{},Timers:[]TimerState{{Name:"Worship",Ready:true,Routine:"claim-worship"}},GreenStacks:[]GreenStackState{{Name:"Copper Ore",Count:5_000_000,Routine:"farm-copper"},{Name:"Oak Logs",Count:10_000_000}}};cfg:=defaultConfig();cfg.Routines["claim-worship"]=Routine{Steps:[]Step{{Type:"click",Point:"claim"}}};cfg.Routines["farm-copper"]=Routine{Steps:[]Step{{Type:"click",Point:"farm"}}};a:=buildAssessmentWithConfig(GameState{Running:true},snap,cfg);if a.TimersReady[0].Automatable||a.GreenStacks[0].Automatable{t.Fatal("uncalibrated routines must not be executable")};cfg.Calibration["claim"]=Point{X:10,Y:10};cfg.Calibration["farm"]=Point{X:20,Y:20};a=buildAssessmentWithConfig(GameState{Running:true},snap,cfg);if !a.TimersReady[0].Automatable||!a.GreenStacks[0].Automatable{t.Fatal("fully calibrated routines should be executable")}}

func TestNormalizeGenericSnapshotAcceptsEfficiencyStyleJSON(t *testing.T){generic:=map[string]any{"accountName":"Kirito","world":float64(7),"alchemy":map[string]any{"progress":float64(.25)},"research":map[string]any{"progress":float64(.4)},"sushiStation":map[string]any{"progress":float64(.2)},"characters":[]any{map[string]any{"name":"Bubo","class":"Bubonic Conjuror","level":float64(500),"active":true}}};s:=normalizeGenericSnapshot(generic,"idleon-efficiency-import");if s.AccountName!="Kirito"||s.World!=7{t.Fatalf("unexpected normalized snapshot: %+v",s)};for _,id:=range []string{"alchemy","research","sushistation"}{if _,ok:=s.Systems[id];!ok{t.Fatalf("expected %s system",id)}};if len(s.Characters)!=1||!s.Characters[0].Active{t.Fatal("expected active character")}}

func TestWorld7CatalogAndCharacterClasses(t *testing.T){for _,id:=range []string{"research","spelunking","coralreef","sushistation"}{rule,ok:=idleonSystems[id];if !ok||rule.MinWorld!=7{t.Fatalf("missing World 7 rule %s",id)}};if normalizeClass("Bubonic Conjuror")!="bubo"||normalizeClass("Divine Knight")!="dk"||normalizeClass("Elemental Sorcerer")!="es"{t.Fatal("elite class normalization failed")}}

func TestFusionPrefersExistingLocalAndFillsMissing(t *testing.T){local:=AccountSnapshot{Source:"local",World:7,AccountName:"K",Systems:map[string]SystemState{"alchemy":{Progress:.7}},Characters:[]CharacterSnapshot{{Name:"A",Class:"Bubo"}},CapturedAt:time.Now()};remote:=AccountSnapshot{Source:"toolbox",World:7,Systems:map[string]SystemState{"alchemy":{Progress:.2},"research":{Progress:.4}}};merged:=mergeSnapshots(local,remote);if merged.Systems["alchemy"].Progress!=.7{t.Fatal("remote source overwrote stronger local data")};if merged.Systems["research"].Progress!=.4{t.Fatal("expected missing remote field to fill")}}
